#include "echoear_network_health.h"
#include <string.h>
static echoear_network_health_t s;
static void clear_probe(void){s.gateway_reachable=false;s.dns_working=false;s.internet_reachable=false;s.last_latency_ms=0;}
static void request_check(uint32_t now){s.check_requested=true;s.state=ECHOEAR_NETWORK_HEALTH_CHECK_REQUESTED;s.next_check_ms=now;s.generation++;}
static uint32_t interval(void){if(s.state==ECHOEAR_NETWORK_HEALTH_INTERNET_READY)return s.policy.healthy_check_interval_ms;if(s.state==ECHOEAR_NETWORK_HEALTH_LOCAL_ONLY)return s.policy.local_only_check_interval_ms;return s.policy.degraded_check_interval_ms;}
echoear_network_health_policy_t echoear_network_health_default_policy(void){echoear_network_health_policy_t p={30000U,5000U,10000U,2U};return p;}
void echoear_network_health_init(void){memset(&s,0,sizeof(s));s.policy=echoear_network_health_default_policy();s.state=ECHOEAR_NETWORK_HEALTH_IDLE;s.error=ECHOEAR_NETWORK_HEALTH_ERROR_NONE;}
void echoear_network_health_reset(void){echoear_network_health_init();}
echoear_network_health_t *echoear_network_health_get(void){return &s;}
void echoear_network_health_set_network_ready(bool ready,uint32_t now){bool changed=s.network_ready!=ready;s.network_ready=ready;if(!ready){s.check_requested=false;s.state=ECHOEAR_NETWORK_HEALTH_OFFLINE;s.error=ECHOEAR_NETWORK_HEALTH_ERROR_NONE;s.consecutive_failures=0;s.consecutive_successes=0;s.next_check_ms=0;clear_probe();if(changed)s.generation++;return;}if(s.state==ECHOEAR_NETWORK_HEALTH_SUSPENDED){if(changed)s.generation++;return;}s.error=ECHOEAR_NETWORK_HEALTH_ERROR_NONE;s.consecutive_failures=0;s.consecutive_successes=0;clear_probe();request_check(now);}
void echoear_network_health_tick(uint32_t now){if(!s.network_ready||s.state==ECHOEAR_NETWORK_HEALTH_SUSPENDED||s.state==ECHOEAR_NETWORK_HEALTH_CHECKING||s.check_requested)return;if(s.next_check_ms==0U||now>=s.next_check_ms)request_check(now);}
bool echoear_network_health_take_check_request(void){if(!s.check_requested)return false;s.check_requested=false;s.state=ECHOEAR_NETWORK_HEALTH_CHECKING;s.generation++;return true;}
void echoear_network_health_report_probe(const echoear_network_health_probe_t *p,uint32_t now){if(!p){s.error=ECHOEAR_NETWORK_HEALTH_ERROR_INVALID_REPORT;s.state=ECHOEAR_NETWORK_HEALTH_ERROR;s.generation++;return;}if(!s.network_ready){s.error=ECHOEAR_NETWORK_HEALTH_ERROR_NOT_READY;s.state=ECHOEAR_NETWORK_HEALTH_OFFLINE;s.generation++;return;}s.gateway_reachable=p->gateway_reachable;s.dns_working=p->dns_working;s.internet_reachable=p->internet_reachable;s.last_latency_ms=p->latency_ms;s.last_check_ms=now;s.check_count++;if(p->gateway_reachable&&p->dns_working&&p->internet_reachable){s.consecutive_failures=0;if(s.consecutive_successes<255)s.consecutive_successes++;s.state=ECHOEAR_NETWORK_HEALTH_INTERNET_READY;s.error=ECHOEAR_NETWORK_HEALTH_ERROR_NONE;}else{s.consecutive_successes=0;if(s.consecutive_failures<255)s.consecutive_failures++;if(!p->gateway_reachable)s.state=ECHOEAR_NETWORK_HEALTH_DEGRADED;else if(!p->internet_reachable&&s.consecutive_failures>=s.policy.failure_confirmations)s.state=ECHOEAR_NETWORK_HEALTH_LOCAL_ONLY;else s.state=ECHOEAR_NETWORK_HEALTH_DEGRADED;s.error=ECHOEAR_NETWORK_HEALTH_ERROR_NONE;}s.next_check_ms=now+interval();s.generation++;}
void echoear_network_health_suspend(void){s.check_requested=false;s.state=ECHOEAR_NETWORK_HEALTH_SUSPENDED;s.generation++;}
void echoear_network_health_resume(bool ready,uint32_t now){s.network_ready=ready;s.error=ECHOEAR_NETWORK_HEALTH_ERROR_NONE;if(!ready){s.state=ECHOEAR_NETWORK_HEALTH_OFFLINE;s.check_requested=false;s.next_check_ms=0;clear_probe();s.generation++;return;}s.consecutive_failures=0;s.consecutive_successes=0;clear_probe();request_check(now);}
void echoear_network_health_clear_error(void){s.error=ECHOEAR_NETWORK_HEALTH_ERROR_NONE;if(!s.network_ready)s.state=ECHOEAR_NETWORK_HEALTH_OFFLINE;else if(s.state==ECHOEAR_NETWORK_HEALTH_ERROR)s.state=ECHOEAR_NETWORK_HEALTH_IDLE;s.generation++;}
bool echoear_network_health_is_internet_ready(void){return s.network_ready&&s.state==ECHOEAR_NETWORK_HEALTH_INTERNET_READY;}
bool echoear_network_health_is_local_available(void){return s.network_ready&&s.gateway_reachable;}
bool echoear_network_health_is_degraded(void){return s.state==ECHOEAR_NETWORK_HEALTH_DEGRADED||s.state==ECHOEAR_NETWORK_HEALTH_LOCAL_ONLY;}
bool echoear_network_health_is_offline(void){return s.state==ECHOEAR_NETWORK_HEALTH_OFFLINE;}
const char *echoear_network_health_state_name(echoear_network_health_state_t v){switch(v){case ECHOEAR_NETWORK_HEALTH_IDLE:return "idle";case ECHOEAR_NETWORK_HEALTH_CHECK_REQUESTED:return "check_requested";case ECHOEAR_NETWORK_HEALTH_CHECKING:return "checking";case ECHOEAR_NETWORK_HEALTH_INTERNET_READY:return "internet_ready";case ECHOEAR_NETWORK_HEALTH_LOCAL_ONLY:return "local_only";case ECHOEAR_NETWORK_HEALTH_DEGRADED:return "degraded";case ECHOEAR_NETWORK_HEALTH_OFFLINE:return "offline";case ECHOEAR_NETWORK_HEALTH_SUSPENDED:return "suspended";case ECHOEAR_NETWORK_HEALTH_ERROR:return "error";default:return "unknown";}}
const char *echoear_network_health_error_name(echoear_network_health_error_t v){switch(v){case ECHOEAR_NETWORK_HEALTH_ERROR_NONE:return "none";case ECHOEAR_NETWORK_HEALTH_ERROR_NOT_READY:return "not_ready";case ECHOEAR_NETWORK_HEALTH_ERROR_INVALID_REPORT:return "invalid_report";case ECHOEAR_NETWORK_HEALTH_ERROR_INTERNAL:return "internal";default:return "unknown";}}
